version: "3"

services:

  mysql:
    image: mysql:5.7.23
    container_name: bookmarks_mysql
    restart: always
    ports:
      - 33060:3306
    restart: always
    environment:
     MYSQL_DATABASE: bookmarks_db
     MYSQL_USER: root
     MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:4.0.11
    container_name: bookmarks_redis
    restart: always
    ports:
      - 63790:6379
